apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ .Values.port }}
