name: Test

on:
  pull_request:
    branches:
    - "main"

jobs:
#  unit-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: '1.18.4'
#
#      - name: Cache
#        uses: actions/cache@v2.1.0
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
#
#      - name: Build
#        run: go build ./...
#
#      - name: Test
#        run: go test ./... -v

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'

      - name: Set up Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          version: v0.14.0
          kubectl_version: v1.22.10
          node_image: kindest/node:v1.22.9
          cluster_name: kind

      - name: kubectl test
        run: |
          kind version
          kubectl version
          echo "current-context:" $(kubectl config current-context)

      - name: Build
        uses: hiberbee/github-action-skaffold@1.22.0
        with:
          working-directory: deploy/
          command: build
          tag: latest

      - name: Upload built image to kind
        run: kind load docker-image ghcr.io/sshota0809/loadbalancerip-mutator:latest

      - name: setup helmfile
        uses: mamezou-tech/setup-helmfile@v1.0.0
        with:
          helmfile-version: 'v0.144.0'
          helm-version: 'v3.9.0'

      - name: install cert-manager
        working-directory: e2e/resource/cert-manager
        run: helmfile apply

      - name: kubectl test
        run: |
          kubectl get ns

      - name: Test
        run: go test ./e2e -v

      - name: Test
        run: kubectl get pods -n webhook