name: Test

on:
  pull_request:
    branches:
    - "main"

jobs:
#  unit-test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: Set up Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: '1.18.4'
#
#      - name: Cache
#        uses: actions/cache@v2.1.0
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
#
#      - name: Build
#        run: go build ./...
#
#      - name: Test
#        run: go test ./... -v

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'

      - name: Set up Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          version: v0.14.0
          kubectl_version: v1.22.10
          node_image: kindest/node:v1.22.9
          cluster_name: e2e-test

      - name: kubectl test
        run: |
          kind version
          kubectl cluster-info
          kubectl get node -o wide
          kubectl get pods -o wide -n kube-system
          kubectl version
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: Test
        run: go test ./e2e -v